global:
route:
  receiver: telegram
  group_by: [alertname, job]
  group_wait: 1m
  group_interval: 5m
  repeat_interval: 1h
  routes:
    - receiver: telegram
      match: 
        severity: default
templates:
- ./templates/*.tmpl

receivers:
  - name: 'telegram'
    telegram_configs:
     - bot_token: '7686091874:AAH1PffffQWZfTE-hfhhggtesthgg'
       api_url: https://api.telegram.org
       chat_id: 538499579
       http_config:
         follow_redirects: true
       disable_notifications: false
       send_resolved: true
       parse_mode: "HTML"
       message: '{{ template "telegram.horibe.message" . }}'
