global:
  scrape_interval: 1m
  scrape_timeout: 30s
  external_labels:
      monitor: "homelab"


rule_files:
  - "rules.EmbeddedExporter.yml"
  - "rules.NodeExporter.yml"
  - "rules.GoogleCadvisor.yml"
  - "rules.NetdataExporter.yml"


alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager.mon:9093"

scrape_configs:

  - job_name: 'prometheus-stack'
    static_configs:
         - targets: ['prometheus.mon:9090','node-exporter.mon:9100','alertmanager.mon:9093']
    metric_relabel_configs:
    - source_labels: [__name__]
      regex: '(prometheus_http_request_duration_seconds_bucket|prometheus_http_response_size_bytes_bucket|alertmanager_notification_latency_seconds_bucket)'
      action: drop


  - job_name: 'grafana-stack'
    metrics_path: /metrics
    static_configs:
      - targets: ['grafana.mon:3000', 'loki.mon:3100', 'promtail.mon:9080']
    metric_relabel_configs:
    - source_labels: [__name__]
      regex: '(grafana_http_request_duration_seconds_bucket)'
      action: drop

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor.mon:8080']

